language: node_js
node_js:
- 9.4.0
install:
- npm install
script:
- npm run script build
before_install:
- openssl aes-256-cbc -K $encrypted_5041a62828b6_key -iv $encrypted_5041a62828b6_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 139.59.124.75\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
